### ISSUE TITLE
[software/gallery] Gallery for parametric generators and art

### ISSUE THREAD

**Issue by exu3** [hackclub/haxidraw#12]
Gallery of function designs and generators with coherent and consistent interfaces.

###### ~~_plottables_~~

This issue tracks the the development of a gallery for community-built parametric art generators and art, similar to [Printables](https://printables.com/) but with the source code available. The details are yet to be fleshed out but ideas are welcome.

**Comment by leomcelroy** [comment]
We've got a maze right now but a flat gallery will be good too.
