### ISSUE TITLE
[hardware/electrical] Make the Modular Things circuits in SVG-PCB

### ISSUE THREAD

**Issue by exu3** [hackclub/haxidraw#4]
The Modular Things circuits can be found [here](https://github.com/modular-things/modular-things-circuits). This issue tracks the translation of those circuits to [SVG-PCB](https://leomcelroy.com/svg-pcb-website/#/home), an in-browser editor that lets you design a PCB from a JavaScript code description.

**Comment by leomcelroy** [comment]
We're going to ship one board with the machine so I'll close this as not planned.
