### ISSUE TITLE
[hardware/electrical] Create a bus

### ISSUE THREAD

**Issue by exu3** [hackclub/haxidraw#5]
**Create a [bus](https://en.wikipedia.org/wiki/Bus_(computing)).** Currently our system uses point-to-point connections. It would be more efficient to design a bus (one-to-many connection) for Modular Things. Some thoughts on [bus design for Modular Things are available here](https://github.com/modular-things/modular-bus). 

###### it seems the repo is private.....

**Comment by leomcelroy** [comment]
Shipping one control board with our machine means we won't need this. In the long term is still a good thing to do but not in our critical path.
