### ISSUE TITLE
[software/firmware] Make visualizer for OSAP networks

### ISSUE THREAD

**Issue by exu3** [hackclub/haxidraw#7]
https://github.com/modular-things/modular-things/tree/main/src/lib/osapjs 

Jake and Leo are working on making OSAP more comprehensible. Leo made a [toy implementaion recreating some of OSAP's functionality](https://github.com/modular-things/nosap). 

Making a visualizer for OSAP networks would be a great project.

**Comment by leomcelroy** [comment]
We're going to ship one control board with the Haxidraw. That means the networking functionality of OSAP isn't neccesary. Still would be an interesting thing to do but not in our critical path so will close this as not planned.
