### ISSUE TITLE
editor erases two characters when i press backspace

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/haxidraw#88]
https://haxidraw.hackclub.dev/editor

when i press "new" and then try to write code, pressing backspace erases two characters at once. 

using chrome version 116.0.5845.168 on chromeOS

**Comment by leomcelroy** [comment]
Nice catch. I noticed this then forgot about it. Looking into it now.

**Comment by leomcelroy** [comment]
This has been addressed in the leo-dev branch. Will merge this week.
